name: Borsa Taraması

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install tradingview-screener pandas requests

      - name: Download previous last_results.csv (if exists)
        uses: actions/download-artifact@v4
        with:
          name: last-results
          path: .
        continue-on-error: true # Artefakt bulunamazsa bile workflow'un devam etmesini sağlar

      - name: Ensure last_results.csv exists
        run: |
          touch last_results.csv

      - name: Run Borsa Taraması Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py

      - name: Upload last_results.csv as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-results
          path: last_results.csv
          if-no-files-found: ignore # last_results.csv oluşturulmamışsa bile hata vermez
